// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "BattleAreaSpline.generated.h"

class USplineComponent;
class UTextRenderComponent;
class USplineMeshComponent;

// V2 editable safe-battlefield boundary. The polygon uses a closed spline: players
// inside any safe spline are allowed; outside it remains forbidden all the way to the
// map edge. A rectangle is generated by default, but designers can move spline points
// in the editor to form a non-rectangular battlefield.
UCLASS()
class MCPGAMEPROJECT_API ABattleAreaSpline : public AActor
{
	GENERATED_BODY()

public:
	ABattleAreaSpline();

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "V2|Spline")
	USplineComponent* BoundarySpline;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "V2|Spline")
	UTextRenderComponent* AreaLabel;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "V2|Spline")
	bool bSafeArea = true;

	// Returns true when a world-space point lies within this closed spline polygon.
	UFUNCTION(BlueprintCallable, Category = "V2|Spline")
	bool IsPointInside(const FVector& WorldPoint) const;

	// Builds a closed safe rectangle using the V2 DataTable extents and draws its border.
	void ConfigureRectangle(float HalfExtentX, float HalfExtentY);

protected:
	virtual void BeginPlay() override;

private:
	void RefreshBoundaryVisuals();
	TArray<USplineMeshComponent*> BoundaryMeshes;
};
